"""LLM enrichment with a fake endpoint: templates, the response store, replay and budgets."""

import csv
import hashlib
import json
import os
import re
from collections import Counter
from pathlib import Path

import pytest
from fixture_model import MODEL, make_mdzip
from helpers import (
    SAMPLES_DIR,
    FakeChat,
    check_invariants,
    project_dir,
    store_db,
    tree,
)

from cameo_ingest.cli import main
from cameo_ingest.prompts import CURRENT


def test_llm_enrichment_is_labelled(tmp_path, fake_chat):
    src = tmp_path / "drone.mdzip"
    src.write_bytes(make_mdzip())
    out = tmp_path / "out"
    assert main([str(src), "-o", str(out), "--vision-model", "gemma-4", "--no-calibrate"]) == 0
    check_invariants(out)  # includes unique chunk ids for the two image descriptions (BASE-002)
    client = fake_chat[0]
    assert len(client.requests) == 4  # preflight, then the diagram and two images: no budget (BASE-019)
    assert [m for m, _ in client.enrichment()] == ["gemma-4"] * 3
    dia = (project_dir(out) / "diagrams/Drone_BDD.md").read_text()
    assert "generated by gemma-4; not part of the source model" in dia
    chunks = [json.loads(line) for line in (out / "chunks.jsonl").open()]
    record = (out / "run.json").read_text()
    assert json.loads(record)["options"]["vision_model"] == "gemma-4"
    assert "api_key" not in (record + (out / "manifest.json").read_text()).lower()
    gen = [c for c in chunks if c["metadata"]["kind"].startswith("generated:")]
    assert gen and all(c["metadata"]["provenance"]["derivation"]["method"] == "llm" for c in gen)
    assert sum(c["metadata"]["kind"] == "generated:image_description" for c in chunks) == 2
    extracted = [c for c in chunks if not c["metadata"]["kind"].startswith("generated:")]
    assert not any("gemma-4" in c["text"] for c in extracted)
    # Structure, not text (AR-012R2): what each answer is about, and an id its pieces share.
    ids = {c["id"] for c in extracted}
    dia_chunk = next(c for c in gen if c["metadata"]["kind"] == "generated:diagram_description")
    assert dia_chunk["metadata"]["primary_chunk"] in ids and dia_chunk["metadata"]["annotation"] == dia_chunk["id"]
    # rag/ holds the generated text too, since it says what a diagram is about (ADR-0029).
    rag = {json.loads(m.read_text())["kind"] for m in (out / "rag" / "meta").glob("*/*.json")}
    assert {"generated:image_description", "generated:diagram_description"} <= rag


def large_package_model() -> str:
    """The fixture model with a package of 40 documented classes: about 45,000 characters."""
    words = "The unit shall report its state to the operator console within the stated interval. " * 8
    classes = "".join(
        f"<packagedElement xmi:type='uml:Class' xmi:id='big{i}' name='Unit {i}'>"
        f"<ownedComment xmi:type='uml:Comment' xmi:id='bigc{i}' body='{words}'><annotatedElement xmi:idref='big{i}'/>"
        "</ownedComment></packagedElement>\n" for i in range(40))
    return MODEL.replace("<uml:Model xmi:type='uml:Model' xmi:id='m1' name='Model'>",
                         "<uml:Model xmi:type='uml:Model' xmi:id='m1' name='Model'>\n"
                         f"<packagedElement xmi:type='uml:Package' xmi:id='bigp' name='Big'>{classes}</packagedElement>")


def test_a_section_too_long_for_a_part_is_split_not_cut(tmp_path, fake_chat):
    """A section longer than a part goes in pieces, each headed by its title and which piece it
    is; every request fits, and nothing is cut (plan TC-01)."""
    import sqlite3

    from cameo_ingest.enrich import pieces, repack
    from cameo_ingest.prompts import PART_CHARS

    text = "Class Unit 7\n" + "\n".join(f"- line {i}: " + "word " * 50 for i in range(200)) + "\n\n" + "x" * 30000
    split = pieces(text)
    assert len(split) > 2 and all(len(p) <= PART_CHARS[1] for p in split)
    assert [p.split("\n")[:2] for p in split[:2]] == [["Class Unit 7", f"Piece: {i} of {len(split)}"] for i in (1, 2)]
    assert "".join(p.split("\n", 2)[2] for p in split).replace("\n", "").replace(" ", "") == \
        text.split("\n", 1)[1].replace("\n", "").replace(" ", "")  # every character of the text, in order
    assert pieces("Class Unit 7\nshort") == ["Class Unit 7\nshort"]
    assert repack(["a", "b"], ["A\nsmall", "B\nsmall"]) == [(["a", "b"], "A\nsmall\n\nB\nsmall")]
    assert [els for els, _ in repack(["a", "b"], ["A\nsmall", text])] == [["a", "b"]] + [["b"]] * (len(split) - 1)

    long_doc = "The unit shall report its state to the operator console within the stated interval. " * 400
    model = large_package_model().replace(
        "<packagedElement xmi:type='uml:Class' xmi:id='big7' name='Unit 7'>",
        "<packagedElement xmi:type='uml:Class' xmi:id='big7' name='Unit 7'>"
        f"<ownedComment xmi:type='uml:Comment' xmi:id='bigl' body='{long_doc}'><annotatedElement xmi:idref='big7'/>"
        "</ownedComment>")
    src = tmp_path / "drone.mdzip"
    src.write_bytes(make_mdzip(model))
    out = tmp_path / "out"
    assert main([str(src), "-o", str(out), "--text-model", "m", "--no-calibrate", "--no-preflight", "--no-render"]) == 0
    report = json.loads((out / "run.json").read_text())["llm"]
    assert "truncated_input" not in report["outcomes"]
    db = sqlite3.connect(store_db())
    prompts = [r[0] for r in db.execute("SELECT slots FROM requests WHERE template LIKE 'module-summary%'")]
    sections = [json.loads(x)["SECTIONS"] for x in prompts]
    assert all(len(x) <= PART_CHARS[1] for x in sections)
    assert sum("Unit 7\nPiece: " in x for x in sections) >= 3  # 34,000 characters of documentation
    assert sum(x.count("operator console") for x in sections) == 40 * 8 + 400  # every sentence, once


def test_the_part_size_is_an_option(tmp_path, fake_chat):
    """`--part-chars` sets the largest input of package text (plan TC-06): smaller parts are more
    of them, each within the size, and the size is in the projects' options."""
    import sqlite3

    src = tmp_path / "drone.mdzip"
    src.write_bytes(make_mdzip(large_package_model()))
    sizes = {}
    for chars in (None, 6000):
        os.environ["CAMEO_INGEST_CACHE"] = str(tmp_path / f"store{chars}")  # each size's own requests
        out = tmp_path / f"out{chars}"
        args = [str(src), "-o", str(out), "--text-model", "m", "--no-calibrate", "--no-preflight", "--no-render"]
        assert main(args + (["--part-chars", str(chars)] if chars else [])) == 0
        db = sqlite3.connect(store_db())
        parts = [json.loads(r[0])["SECTIONS"] for r in db.execute(
            "SELECT slots FROM requests WHERE template LIKE 'module-summary%' AND item LIKE '%bigp%'")]
        assert parts and all(len(x) <= (chars or 12000) for x in parts)
        sizes[chars] = len(parts)
        assert json.loads((out / "run.json").read_text())["options"]["part_chars"] == (chars or 12000)
    assert sizes[6000] > sizes[None]


def test_large_package_parts(tmp_path, fake_chat, monkeypatch):
    """A large package is summarized in parts, then from its parts' summaries, through runs of
    them when there are many; each part's summary is a chunk naming its elements (FU-005,
    plan DV-05)."""
    import sqlite3

    from cameo_ingest import enrich

    monkeypatch.setattr(enrich, "MAX_SUMMARIES", 2)  # so that parts are summarized in runs first
    src = tmp_path / "drone.mdzip"
    src.write_bytes(make_mdzip(large_package_model()))
    out = tmp_path / "out"
    assert main([str(src), "-o", str(out), "--text-model", "m", "--no-calibrate", "--no-preflight", "--no-render"]) == 0
    check_invariants(out)
    page = (project_dir(out) / "packages/Model__Big.md").read_text()
    assert "## Parts, summarized" in page and '<a id="part-1"></a>' in page and re.search('<a id="parts-\\d+-\\d+">', page)
    chunks = [json.loads(line) for line in (out / "chunks.jsonl").open()]
    parts = [c["metadata"]["covers"] for c in chunks if c["metadata"]["kind"] == "generated:module_summary"]
    singles = [p for p in parts if p["number"] == p["last"]]
    n = singles[0]["of"]
    assert 3 <= n <= 15 and [p["number"] for p in singles] == list(range(1, n + 1))
    assert all(p["last"] > p["number"] for p in parts if p not in singles)  # no run of a single part
    assert sorted(e for p in singles for e in p["elements"]) == sorted(f"big{i}" for i in range(40))
    assert singles[0]["anchor"] == "packages/Model__Big.md#part-1"
    # Headings read like any plain chunk's (AR-004R1), the names they cover cut to fit (AR-004R2).
    from cameo_ingest import plain as pl

    part1 = next(c for c in chunks if c["metadata"].get("covers") == singles[0])
    heading = part1["text"].split("\n", 1)[0]
    assert heading.startswith("Part summary of Package Big in Model (project drone [") and ", part 1 of " in heading
    assert ", covering Unit 0; Unit 1" in heading and heading.endswith("not part of the source model)"), heading
    assert pl.tokens(heading) <= pl.HEADING
    summary = [c for c in chunks if c["metadata"]["kind"] == "generated:summary" and c["metadata"]["element_id"] == "bigp"]
    assert summary[0]["text"].startswith("Summary of Package Big in Model (project drone [")
    assert [c["metadata"]["provenance"]["derivation"]["template"] for c in summary] == [CURRENT["package-synthesis"].key]
    db = sqlite3.connect(store_db())
    used = Counter(r[0] for r in db.execute("SELECT template FROM requests WHERE item LIKE '%bigp%'"))
    synthesis = CURRENT["package-synthesis"].key
    assert used[CURRENT["module-summary"].key] == n and used[synthesis] == len(parts) - n + 1
    prompt = db.execute("SELECT prompt FROM requests WHERE template = ? ORDER BY rowid DESC", (synthesis,)).fetchone()[0]
    assert "descriptions of the whole package" in prompt and re.search(r"\nParts \d+ to \d+: ", prompt)


def instances_model() -> str:
    """The fixture model with a package of analysis results: a run and 60 instances of Battery
    whose slots set a value, about 20,000 characters."""
    instances = "".join(
        f"<packagedElement xmi:type='uml:InstanceSpecification' xmi:id='in{i}' name='run.battery pack.cell{i}'>"
        f"<classifier xmi:idref='b2'/><slot xmi:type='uml:Slot' xmi:id='sl{i}'><definingFeature xmi:idref='a1'/>"
        f"<value xmi:type='uml:LiteralReal' xmi:id='lv{i}' value='{i % 3}.5'/></slot></packagedElement>\n"
        for i in range(60))
    run = ("<packagedElement xmi:type='uml:InstanceSpecification' xmi:id='inrun' name='run at 2026.01.01'>"
           "<classifier xmi:idref='b1'/><slot xmi:type='uml:Slot' xmi:id='slrun'><definingFeature xmi:idref='a1'/>"
           "<value xmi:type='uml:InstanceValue' xmi:id='ivrun' instance='in0'/></slot></packagedElement>\n")
    return MODEL.replace("<uml:Model xmi:type='uml:Model' xmi:id='m1' name='Model'>",
                         "<uml:Model xmi:type='uml:Model' xmi:id='m1' name='Model'>\n"
                         f"<packagedElement xmi:type='uml:Package' xmi:id='resp' name='Results'>{run}{instances}"
                         "</packagedElement>")


def test_instance_packages_summarized_from_a_digest(tmp_path, fake_chat):
    """A large package made mostly of instance specifications is summarized in one request,
    from a digest of its instances, not in parts (FU-022)."""
    import sqlite3

    src = tmp_path / "drone.mdzip"
    src.write_bytes(make_mdzip(instances_model()))
    out = tmp_path / "out"
    assert main([str(src), "-o", str(out), "--text-model", "m", "--no-calibrate", "--no-preflight", "--no-render"]) == 0
    check_invariants(out)
    page = (project_dir(out) / "packages/Model__Results.md").read_text()
    assert "- **Classifier:** [Battery]" in page and "## Parts, summarized" not in page
    db = sqlite3.connect(store_db())
    rows = db.execute("SELECT template, prompt FROM requests WHERE item LIKE '%resp%'").fetchall()
    assert [r[0] for r in rows] == [CURRENT["instances-summary"].key]
    prompt = rows[0][1]
    assert "61 instance specifications of 2 classifiers." in prompt
    # The run's slot refers to cell 0 only, so the other cells are top-level too.
    assert "Top-level instances: run at 2026.01.01; run.battery pack.cell1; " in prompt
    assert "- Battery: 60 instances, such as run.battery pack.cell0" in prompt
    assert "slot battery, set 60 times: 0.5, 1.5, 2.5" in prompt
    assert "slot battery, set 1 time: an instance of Battery" in prompt


def test_current_templates_pinned():
    """A template's request never changes under its key: a new text, or a new fragment, is a new
    version, so that projects written with the old one are written again (FU-014). Pinned by hash
    (plan RA-03): those in use, and plan GS's variants, which text calibration and experiments
    still send."""
    from cameo_ingest import prompts

    def pin(t) -> str:  # its text and, when it has them, its fragments (AR-009)
        return hashlib.sha256(f"{t.image_first}|{t.text}{f'|{t.fragments}' if t.fragments else ''}".encode()).hexdigest()[:16]

    assert {k: pin(t) for k, t in prompts._ALL.items()} == {
        "diagram-description@v6": "febe4654a66e0acc",
        "diagram-description@v7": "eda9cbc23f3d6076",
        "diagram-description@v8": "727eda672139d095",
        "diagram-description@v9": "7a3b7d8fb1309b8c",
        "diagram-synthesis@v2": "864e9e9b3a1a3ce1",
        "diagram-synthesis@v3": "e3e5efa10ac930fb",
        "diagram-synthesis@v4": "78c4657b315768f0",
        "diagram-synthesis@v5": "563eca6d82c882e5",
        "image-description@v2": "abc49bf5c21deb2c",
        "instances-summary@v2": "7efe4dab7b5f2f97",
        "instances-summary@v3": "2f2a19338fa7efed",
        "instances-summary@v4": "bb81e109c4617ae0",
        "instances-summary@v5": "b3c3c19aabf41561",
        "module-description@v3": "5d339bf2c19fb77b",
        "module-summary@v3": "adb1988426c52a72",
        "module-summary@v4": "246b48d1906dfed5",
        "module-summary@v5": "2c6c7cfc573083ef",
        "module-summary@v6": "45a0ce417b32b23f",
        "package-summary@v4": "9b211fbe74c3e128",
        "package-summary@v5": "797d166274e7554b",
        "package-summary@v6": "d19378ed521bd633",
        "package-summary@v7": "fb8e71f9c2eec229",
        "package-synthesis@v3": "ffde10093ba92d11",
        "package-synthesis@v4": "8bb6fce095e9c98c",
        "package-synthesis@v5": "5f617d45cf432a5f",
        "package-synthesis@v6": "f1da2b0e496fe805",
    }
    assert sorted(t.key for t in prompts.CURRENT.values()) == [
        "diagram-description@v9", "diagram-synthesis@v5", "image-description@v2", "instances-summary@v5",
        "module-description@v3", "module-summary@v6", "package-summary@v7", "package-synthesis@v6"]


def test_templates_and_request_log(tmp_path, fake_chat):
    """Prompts are named, versioned templates with described slots (plan LQ-01), and every
    request is logged with what it asked (LQ-02)."""
    import sqlite3

    from cameo_ingest.prompts import TEMPLATES

    for key, tpl in TEMPLATES.items():
        text_slots = [s.name for s in tpl.slots if s.kind == "text"]
        assert "{{" not in tpl.render({s: "x" for s in text_slots}), key
        shown = tpl.stand_in()
        assert all(f"⟦{s.name}" in shown or f"⟦IMAGE {s.name}" in shown for s in tpl.slots), key
    src = tmp_path / "drone.mdzip"
    src.write_bytes(make_mdzip())
    out = tmp_path / "out"
    assert main([str(src), "-o", str(out), "--text-model", "m", "--no-calibrate", "--no-preflight"]) == 0
    token = f"sha256:{project_dir(out).name}"
    db = sqlite3.connect(store_db())
    rows = db.execute("SELECT template, project, item, image_path, prompt, notes FROM requests ORDER BY template, "
                      "image_path").fetchall()
    assert [(r[0], r[3]) for r in rows] == [(CURRENT["diagram-description"].key, "diagrams/Drone_BDD.png"),
                                           ("image-description@v2", "images/BINARY-img1.png"),
                                           ("image-description@v2", "images/BINARY-img2.png"),
                                           (CURRENT["package-summary"].key, None)]
    assert all(r[1] == token and r[2].startswith(token[:23]) for r in rows)
    assert rows[0][4].startswith(CURRENT["diagram-description"].text.split("{{")[0])
    assert "Diagram: Drone BDD (SysML Block Definition Diagram)" in rows[0][4]
    chunks = [json.loads(line) for line in (out / "chunks.jsonl").open()]
    templates = {c["metadata"]["provenance"]["derivation"].get("template") for c in chunks
                 if c["metadata"]["kind"].startswith("generated:")}
    assert templates == {CURRENT["diagram-description"].key, "image-description@v2", CURRENT["package-summary"].key}
    # The image goes before the text (FU-015).
    request = json.loads(json.dumps(fake_chat[0].enrichment()[0][1]))
    assert [part["type"] for part in request[0]["content"]] == ["image_url", "text"]


def test_quality_sample(tmp_path, fake_chat, capsys):
    """A spot-check set shows each template with stand-ins, and each item with its request,
    image, response, and reference without the response (plan LQ-03)."""
    src = tmp_path / "drone.mdzip"
    src.write_bytes(make_mdzip())
    out = tmp_path / "out"
    assert main([str(src), "-o", str(out), "--text-model", "m", "--no-calibrate", "--no-preflight"]) == 0
    drawn = []
    for _ in range(2):  # the same seed draws the same items
        assert main(["quality", "sample", "-o", str(out), "--n", "3", "--seed", "7"]) == 0
        set_dir = Path(capsys.readouterr().out.split("spot-check set ")[1].split(":")[0])
        items = [json.loads(line) for line in (set_dir / "items.jsonl").open()]
        drawn.append((set_dir.name, [i["id"] for i in items]))
    assert drawn[0][1] == drawn[1][1] and drawn[0][0] != drawn[1][0]
    assert sorted(i["kind"] for i in items) == ["diagram_description", "image_description", "summary"]
    for it in items:
        assert it["response"] and it["response"] not in it["reference"], it["kind"]
    summary = next(i for i in items if i["kind"] == "summary")
    assert "Model::Structure" in summary["prompt"] and summary["image"] is None
    page = (set_dir / "index.html").read_text()
    assert '<span class="slot">⟦LEGEND:' in page and '<span class="slot">⟦IMAGE SKETCH' in page
    assert page.count("src='data:image/png;base64,") == 2  # the diagram sketch and the embedded image
    with (set_dir / "rate-items.csv").open() as f:
        assert [r["item"] for r in csv.DictReader(f)] == [i["id"] for i in items]
    with (set_dir / "rate-templates.csv").open() as f:
        assert {r["template"] for r in csv.DictReader(f)} == {i["template"] for i in items}
    # The reference drops the answer under any label, a part summary's among them (AR-012).
    from cameo_ingest.quality import _reference

    (out / "big.md").write_text("---\ntitle: P\n---\n# Package P\n\n**Summary of parts 1 to 3** _(generated by m; "
                                "not part of the source model)_:\n\nIt pumps.\n\n**Members:**\n")
    assert _reference(out, "big.md#p", "m", "It pumps.") == "# Package P\n\n\n**Members:**\n"


def test_llm_call_budget(tmp_path, fake_chat):
    src = tmp_path / "drone.mdzip"
    src.write_bytes(make_mdzip())
    out = tmp_path / "out"
    assert main([str(src), "-o", str(out), "--vision-model", "m", "--no-calibrate", "--llm-max-calls", "1"]) == 0
    assert len(fake_chat[0].enrichment()) == 1
    report = json.loads((out / "run.json").read_text())["llm"]
    assert report["calls"] == 1 and report["outcomes"]["skipped_budget"] == 2
    assert all(i["item"].startswith("sha256:") for i in report["incomplete"])


def test_llm_store_and_replay(tmp_path, fake_chat, monkeypatch):
    src = tmp_path / "drone.mdzip"
    src.write_bytes(make_mdzip())
    store = tmp_path / "store"
    args = [str(src), "--vision-model", "m", "--no-calibrate", "--cache-dir", str(store), "--meta", "program=test"]
    trees = []
    for i in range(2):  # the second run is answered from the store (BASE-005)
        out = tmp_path / f"out{i}"
        assert main([*args, "-o", str(out)]) == 0
        trees.append(tree(out))
    report = json.loads((out / "run.json").read_text())["llm"]
    assert report["calls"] == 0 and report["outcomes"] == {"cached": 3}
    # Replay never touches the network; it reproduces the recorded run exactly (BASE-022R5).
    monkeypatch.setattr(FakeChat, "fail", True)
    out = tmp_path / "replayed"
    assert main([str(src), "--vision-model", "m", "--no-calibrate", "--llm-replay", str(store / "llm.sqlite"),
                 "--meta", "program=test", "-o", str(out)]) == 0
    assert json.loads((out / "run.json").read_text())["llm"]["outcomes"] == {"replayed": 3}
    assert tree(out) == trees[1]
    assert len(fake_chat) == 2  # no client at all in replay mode
    # A request the store has no answer for fails the project, loudly.
    out = tmp_path / "missed"
    assert main([str(src), "--vision-model", "other", "--no-calibrate", "--llm-replay", str(store / "llm.sqlite"),
                 "-o", str(out)]) == 4
    assert "ReplayMiss: no recorded other response" in json.loads((out / "manifest.json").read_text())["failed"][0]["error"]


def test_llm_store_corrupt(tmp_path, fake_chat, caplog, monkeypatch):
    import sqlite3

    store = tmp_path / "store"
    store.mkdir()
    (store / "llm.sqlite").write_bytes(b"not a database, e.g. a file cut short by a killed run")
    src = tmp_path / "drone.mdzip"
    src.write_bytes(make_mdzip())
    out = tmp_path / "out"
    assert main([str(src), "-o", str(out), "--vision-model", "m", "--no-calibrate",
                 "--cache-dir", str(store)]) == 0  # BASE-005
    assert "is unreadable" in caplog.text and list(store.glob("llm.sqlite.corrupt-*"))
    assert sqlite3.connect(store / "llm.sqlite").execute("SELECT count(*) FROM responses").fetchone() == (3,)
    # A store that fails to keep a paid answer costs a re-ask later, not the project (AR-016).
    from cameo_ingest.llm import ResponseStore

    def broken(*_a):
        raise sqlite3.OperationalError("disk I/O error")

    monkeypatch.setattr(ResponseStore, "put", broken)
    out = tmp_path / "out2"
    assert main([str(src), "-o", str(out), "--vision-model", "other", "--no-calibrate", "--cache-dir", str(store)]) == 0
    assert "cannot store LLM response" in caplog.text
    assert json.loads((out / "run.json").read_text())["llm"]["outcomes"] == {"answered": 3}


def test_llm_circuit_breaker(tmp_path, fake_chat, monkeypatch):
    monkeypatch.setattr(FakeChat, "fail", True)
    src = tmp_path / "drone.mdzip"
    src.write_bytes(make_mdzip())
    out = tmp_path / "out"
    # Four items (a diagram, two images, a package summary); the endpoint fails every request.
    assert main([str(src), "-o", str(out), "--text-model", "m", "--no-calibrate", "--no-preflight"]) == 0
    assert len(fake_chat[0].requests) == 3  # then enrichment is switched off (BASE-006)
    report = json.loads((out / "run.json").read_text())["llm"]
    assert report["disabled_after_failures"] and report["outcomes"] == {"failed": 3, "skipped_disabled": 1}
    assert report["incomplete"][0]["detail"] == "RuntimeError: endpoint down"


REPLAY = Path(__file__).parent / "fixtures" / "llm-replay.sqlite"


@pytest.mark.skipif(not REPLAY.exists(), reason="no recorded LLM fixture (scripts/record_llm_fixture.py)")
@pytest.mark.parametrize("sample", ["fixture", "Package_Delivery_Drone.mdzip"])
def test_replay_recorded_llm(tmp_path, sample):
    """Real model answers, recorded by scripts/record_llm_fixture.py, replayed offline
    (BASE-022R5). A ReplayMiss here means a prompt or the input changed: record again."""
    import sqlite3

    if sample == "fixture":
        src = tmp_path / "drone.mdzip"
        src.write_bytes(make_mdzip())
    else:
        src = SAMPLES_DIR / sample
        if not src.exists():
            pytest.skip("sample not fetched (scripts/fetch_samples.py --small)")
    db = sqlite3.connect(f"file:{REPLAY}?mode=ro", uri=True)
    model = db.execute("SELECT model FROM responses LIMIT 1").fetchone()[0]
    db.close()
    out = tmp_path / "out"
    assert main([str(src), "-o", str(out), "--no-render", "--no-calibrate", "--text-model", model,
                 "--llm-replay", str(REPLAY)]) == 0
    check_invariants(out)
    report = json.loads((out / "run.json").read_text())["llm"]
    assert report["incomplete"] == [] and set(report["outcomes"]) == {"replayed"}  # and nothing cut (plan TC-01)
    gen = [c for c in map(json.loads, (out / "chunks.jsonl").open()) if c["metadata"]["kind"].startswith("generated:")]
    assert gen and all(c["metadata"]["provenance"]["derivation"]["model"] == model for c in gen)


def test_llm_concurrency(tmp_path, fake_chat, monkeypatch):
    monkeypatch.setattr(FakeChat, "delay", 0.1)
    monkeypatch.setattr(FakeChat, "max_inflight", 0)
    src = tmp_path / "drone.mdzip"
    src.write_bytes(make_mdzip())
    trees = []
    for n in (1, 3):
        out = tmp_path / f"out{n}"
        assert main([str(src), "-o", str(out), "--vision-model", "m", "--cache-dir", str(tmp_path / f"store{n}"),
                     "--llm-concurrency", str(n)]) == 0
        trees.append(tree(out))
    assert FakeChat.max_inflight >= 2  # requests overlapped (BASE-019R4)...
    assert trees[0] == trees[1]  # ...and the output is the same as a sequential run


def test_every_template_filled_by_its_builder():
    """Every current template, filled by its builder (prompt_values) on the fixture, leaves no
    slot unfilled, and each cut adds its template's own fragment (AR-009R3)."""
    import hashlib
    import tempfile

    from test_diagrams import large_layout

    from cameo_ingest import prompt_values as pv
    from cameo_ingest.archive import discover
    from cameo_ingest.emit import ProjectWriter
    from cameo_ingest.pipeline import load_layouts, parse_project
    from cameo_ingest.prompts import CURRENT, PART_CHARS
    from cameo_ingest.provenance import ContentInfo

    data = make_mdzip(instances_model(), large_layout())
    project = next(discover(data, "drone.mdzip"))
    ix = parse_project(project)
    with tempfile.TemporaryDirectory() as tmp:
        w = ProjectWriter(ContentInfo(hashlib.sha256(data).hexdigest(), "drone.mdzip"), project, ix, Path(tmp), {},
                          load_layouts(project, ix), (25, 6, 25))
        dia = next(iter(w.view.layouts))
        g, part, d = w.view.graph(dia), w.view.partition(dia), ix.diagrams[dia]
        pkg = next(e for e in ix.elements.values() if e.kind == "Package" and any(
            c.kind == "InstanceSpecification" for c in w.view.sections_in(e)))
        sections = w.view.sections_in(pkg)
        own, texts = w.view.section_view(pkg).text(), [w.view.section_view(e).text() for e in sections]
        filled = {
            "diagram-description": pv.diagram_description(ix, g, d),
            "module-description": pv.module_description(ix, part, 1, d),
            "diagram-synthesis": pv.diagram_synthesis(ix, part, d, ["It pumps."] * len(part.modules)),
            "image-description": pv.image_description(),
            "package-summary": pv.package_summary("\n\n".join([own, *texts])),
            "module-summary": pv.module_summary("Model::P", 1, 2, "x" * (PART_CHARS[1] + 1)),
            "package-synthesis": pv.package_synthesis("Model::P", [3, 4], own, [((1, 1), "A."), ((2, 2), None)], True),
            "instances-summary": pv.instances_summary(ix, "Model::P", own, sections, texts),
        }
    assert set(filled) == set(CURRENT)
    from cameo_ingest.enrich import with_context

    for tid, v in filled.items():  # with the context, as the enricher adds it (plan GS)
        assert "{{" not in CURRENT[tid].render(with_context(CURRENT[tid], v.values, lambda: "(none)")), tid
    small = pv.instances_summary(ix, "Model::P", own, sections, texts, part_chars=300)  # follows the part size
    assert small.values["DIGEST"].endswith(CURRENT["instances-summary"].fragment("cut"))
    assert len(small.values["DIGEST"]) <= 200 + len(CURRENT["instances-summary"].fragment("cut"))
    assert filled["instances-summary"].values["DIGEST"] != small.values["DIGEST"]
    assert filled["module-summary"].values["CUT_NOTE"] == CURRENT["module-summary"].fragment(
        "cut", limit=PART_CHARS[1], length=PART_CHARS[1] + 1) and filled["module-summary"].cut
    assert filled["diagram-description"].values["DIAGRAM"].endswith(")") and "(None)" not in filled[
        "diagram-description"].values["DIAGRAM"]


def test_a_candidate_request_classifies_its_answer(tmp_path, monkeypatch):
    """A plan GS variant asks what a package or diagram is about, with context; its answer's first
    line is its class, which the chunk's metadata keeps, and the text goes on without it."""
    from cameo_ingest import llm, prompts

    class Classifying(FakeChat):
        def complete(self, model, messages, temperature):
            super().complete(model, messages, temperature)
            asks = "on a line of its own, classify" in json.dumps(messages)
            return "**Class:** Structure\n\nWhat the drone is made of." if asks else "A diagram."

    import importlib.util

    made: list[FakeChat] = []
    monkeypatch.setattr(llm, "OpenAIChat", lambda cfg: made.append(Classifying(cfg)) or made[-1])
    for key in prompts.VARIANTS["about/context"]:  # the templates in use come back after the test
        monkeypatch.setitem(prompts.CURRENT, key, prompts.CURRENT[key])
    spec = importlib.util.spec_from_file_location("build_variant",
                                                  Path(__file__).parent.parent / "scripts" / "build_variant.py")
    script = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(script)
    src = tmp_path / "drone.mdzip"
    src.write_bytes(make_mdzip())
    out = tmp_path / "out"
    assert script.main(["about/context", str(src), "-o", str(out), "--text-model", "m", "--vision-model", "m",
                        "--no-calibrate", "--no-preflight"]) == 0
    assert prompts.CURRENT["package-summary"].key == "package-summary@v7"
    texts = [json.dumps(m) for _, m in made[0].enrichment()]
    diagram = next(t for t in texts if "classify the diagram" in t)
    assert "For context only, what the diagram's context and its shapes are" in diagram and "- [1] " in diagram
    chunks = [json.loads(line) for line in (out / "chunks.jsonl").open()]
    dia = next(c for c in chunks if c["metadata"]["kind"] == "generated:diagram_description")
    assert dia["metadata"]["about_class"] == "structure" and "Class" not in dia["text"]
    assert dia["text"].endswith("What the drone is made of.")
    assert all("about_class" not in c["metadata"] for c in chunks if not c["metadata"]["kind"].startswith("generated:"))


def test_package_context():
    """What a package's request may be told of its place (plan GS): the packages around it,
    outermost first, and the documented elements outside it that its elements refer to most."""
    import io

    from cameo_ingest import prompt_values as pv
    from cameo_ingest.evaluation.fiction import PROJECTS
    from cameo_ingest.model import ModelIndex
    from cameo_ingest.xmi import finalize, parse_into

    p = PROJECTS["pct"]()
    ix = ModelIndex()
    parse_into(ix, io.BytesIO(p.xmi().encode()), "com.nomagic.magicdraw.uml_model.model")
    finalize(ix)
    corridor = next(e.id for e in ix.elements.values() if e.name == "Corridor Harbour Road")
    lines = pv.package_context(ix, corridor).splitlines()
    assert lines[:4] == [
        "The model Port Calder Traffic Signal System",
        ("Within Port Calder Signals: The city of Port Calder's traffic signals: field equipment, corridors and the "
         "central system."),
        "Within Signal Network: The six signal corridors and their intersections.",
        "It refers to:"]
    assert "- Class Meridian ATC-5: The current standard controller, with an Ethernet uplink to the ATMS." in lines
    assert pv.package_context(ix, next(e.id for e in ix.elements.values() if e.kind == "Model")) == "(none)"


def test_a_trees_own_store_joins_the_shared_store(tmp_path, fake_chat, monkeypatch):
    """The LLM store is per user (plan CF-04); a tree's own store, from before, is copied into it
    once, so that nothing it paid for is asked again."""
    import shutil

    from cameo_ingest.state import State

    src = tmp_path / "drone.mdzip"
    src.write_bytes(make_mdzip())
    out = tmp_path / "out"
    args = [str(src), "-o", str(out), "--vision-model", "m", "--no-calibrate", "--no-preflight"]
    assert main(args) == 0
    (out / ".cache").mkdir()
    shutil.copy(store_db(), out / ".cache" / "llm.sqlite")  # as 0.20.1 and before kept it
    os.environ["CAMEO_INGEST_CACHE"] = str(tmp_path / "new-store")
    from cameo_ingest import runner

    monkeypatch.setattr(runner, "TOOL", "cameo-ingest/99")  # every project written again, asking the same
    assert main(["run", "-o", str(out), "--no-preflight"]) == 0
    outcomes = json.loads((out / "run.json").read_text())["llm"]["outcomes"]
    assert "answered" not in outcomes and outcomes.get("cached"), outcomes
    st = State(out)
    assert st.meta("store_adopted") == str(tmp_path / "new-store")
    st.close()
