"""Plain chunk text for embedding (plan RE-08, decisions 6 and 11; `--chunk-style plain`).

The Markdown of the pages serves readers: links with their targets, trace lines, qualified names.
In a chunk, that apparatus fills the embedding window (45% of the characters, RE-01), and the
production stack cuts long chunks into windows that lose their heading. In the plain style:
- **text:** links reduced to their labels, no trace line (the metadata holds the provenance), no
  Markdown markers;
- **heading:** what the item is, its name (a requirement's id and text when it has no name),
  where it is (the last packages of its path) and the project;
- **meaning apart from structure:** an element's meaning (its requirement text, documentation,
  relationships, diagrams) first, its structural detail (members, tagged values) after it, in
  the same chunk when the whole fits in one part, else in a details chunk of its own. (A short
  details chunk is mostly heading, so it outranks the element's meaning for its name: RE-08.)
- **parts:** text that won't fit in one embedding window is split at line boundaries, each part
  repeating the heading, so that every window says whose text it is. The budget is in tokens,
  estimated (`tokens`), since text dense with ids makes two or three times more tokens per
  character than prose; it leaves room for the source line that `rag/` files end with.
"""

from __future__ import annotations

import math
import re

from .text import md_plain, one_line

WINDOW = 512  # the embedding window parts are made for (e5, bge, ember-v1)
SOURCE = 100  # tokens left free for a rag/ file's source line (a trace locator: 70 to 80 tokens)
BUDGET = WINDOW - SOURCE - 12  # tokens of heading and text per part, as `tokens` estimates them
_TOKEN = re.compile(r"[A-Za-z]+|[0-9]+|[^\sA-Za-z0-9]")
_LINK = re.compile(r"\[((?:[^\[\]\\]|\\.)*)\]\([^)]*\)")
_TRACE = re.compile(r"[ \t]*<sub>trace: `[^`]*`</sub>[ \t]*")
# The block labels emit writes: "**Documentation:**", "**Connections (12):**", "**Specification
# (OCL2.0):**", "**Table / matrix configuration** (rows ...):", "**Summary** _(generated by ...)_:".
_BLOCK = re.compile(r"^\*\*([^*]+?)(?: \(([^)]*)\))?(?::\*\*|\*\* (?:\([^)\n]*\)|_\([^)\n]*\)_):)\s*(.*)$")
# Emit's emphasis, and only that, so that model text keeps its operators (AR-003): bold around a
# label or name ("**Kind:**", "**REQ-1**"), a member's role in italics ("- *part* ..."), an
# annotation's origin ("_(generated by ...)_").
_BOLD = re.compile(r"(?<![\w*\\])\*\*(?=\S)((?:[^*\n\\]|\\.)+?)(?<=\S)\*\*(?![\w*])")
_ROLE = re.compile(r"^(\s*- )\*(?=\S)([^*\n]+?)(?<=\S)\* ", re.MULTILINE)
_ORIGIN = re.compile(r"(?<!\w)_\(([^)\n]*)\)_")
_QUOTE = re.compile(r"^> ?", re.MULTILINE)
DETAIL_BLOCKS = ("Members", "Tagged values")
QUOTED_BLOCKS = ("Requirement text",)  # emit quotes these with "> "


def tokens(text: str) -> int:
    """About how many tokens a 512-token embedding model makes of `text`. Fitted to the
    tokenizer of multilingual-e5-large on the samples' chunks (words, long words, digits,
    punctuation), then raised by a fifth, so that it is too low for fewer than 4% of chunks."""
    n = 0.0
    for w in _TOKEN.findall(text):
        if w[0].isalpha():
            n += 1.07 + 0.415 * max(0, len(w) - 6)
        elif w[0].isdigit():
            n += 0.42 + 0.375 * len(w)
        else:
            n += 0.95
    return math.ceil(1.2 * n)


def _cut(line: str, room: int) -> tuple[str, str]:
    """A line too long for a part: as much of it as fits in `room` tokens (at a space where
    there is one in its second half), and the rest."""
    lo, hi = 1, len(line)
    while lo < hi:  # the longest prefix that fits
        mid = (lo + hi + 1) // 2
        if tokens(line[:mid]) <= room:
            lo = mid
        else:
            hi = mid - 1
    space = line.rfind(" ", 0, lo + 1)
    end = space if space > lo // 2 else lo
    return line[:end].rstrip(), line[end:].lstrip()


def plain(md: str) -> str:
    """Markdown as plain text: links to their labels, no trace lines, no emphasis or code marks.
    Only the markup emit writes is removed; model text keeps its characters."""
    text = _TRACE.sub("", md)
    text = _LINK.sub(r"\1", text)
    text = _BOLD.sub(r"\1", text)
    text = _ROLE.sub(r"\1\2 ", text)
    text = _ORIGIN.sub(r"(\1)", text)
    text = text.replace("```", "").replace("`", "")
    text = md_plain(text)
    return re.sub(r"\n{3,}", "\n\n", text).strip()


def blocks(md: str) -> tuple[list[str], list[tuple[str, list[str]]]]:
    """A section's header lines (the bullets under its title) and its blocks, in order, each a
    name and its lines; the title and trace lines are dropped. A block's name keeps what its label
    says in parentheses, unless that is a count ("Specification (OCL2.0)", "Connections")."""
    header: list[str] = []
    out: list[tuple[str, list[str]]] = []
    for line in md.splitlines():
        if (line.startswith("#") and not out) or _TRACE.fullmatch(line):  # the title, not text in a block
            continue
        m = _BLOCK.match(line)
        if m:
            name, note = m.group(1), m.group(2)
            out.append((f"{name} ({note})" if note and not note.isdigit() else name,
                        [m.group(3)] if m.group(3) else []))
        elif out:
            out[-1][1].append(line)
        elif line.strip():
            header.append(line)
    return header, out


def where(owner: str, project: str) -> str:
    """'in A::B::C (project X)': the last three packages of the owner's qualified name, and the
    project."""
    path = "::".join(owner.split("::")[-3:]) if owner else ""
    return (f"in {path} " if path else "") + f"(project {project})"


def parts(heading: str, text: str, budget: int = BUDGET) -> list[str]:
    """`text` under `heading`, split at line boundaries into parts of at most about `budget`
    tokens with the heading (and its part number), each repeating the heading."""
    room = max(budget - tokens(heading) - 8, 40)
    out: list[list[str]] = [[]]
    size = 0
    for line in text.splitlines():
        while tokens(line) > room:  # a line too long for any part: cut it
            head, line = _cut(line, room)
            if out[-1]:
                out.append([])
            out[-1].append(head)
            out.append([])
            size = 0
        n = tokens(line) + 1
        if size + n > room and out[-1]:
            out.append([])
            size = 0
        out[-1].append(line)
        size += n
    chunks = ["\n".join(p).strip() for p in out]
    chunks = [c for c in chunks if c]
    if len(chunks) <= 1:
        return [f"{heading}\n\n{chunks[0]}" if chunks else heading]
    return [f"{heading} (part {k} of {len(chunks)})\n\n{c}" for k, c in enumerate(chunks, 1)]


def section(md: str, heading: str) -> tuple[list[str], list[str]]:
    """An element's section (Markdown, as on its page) as plain parts: (meaning, details)."""
    header, bs = blocks(md)
    fields = [plain(h).removeprefix("- ") for h in header
              if not h.startswith(("- **Kind:**", "- **Qualified name:**"))]
    meaning = fields[:]
    detail: list[str] = []
    for name, lines in bs:
        text = plain("\n".join(lines))
        if name in QUOTED_BLOCKS:
            text = _QUOTE.sub("", text)
        if not text:
            continue
        target = detail if name in DETAIL_BLOCKS else meaning
        inline = "\n" not in text and len(text) < 200 and not text.startswith("- ")  # lists keep their lines
        target.append(f"{name}: {one_line(text)}" if inline else f"{name}:\n{text}")
    together = "\n".join(meaning + detail)
    if tokens(heading) + tokens(together) + 8 <= BUDGET:
        return parts(heading, together), []
    # Always a meaning chunk: the heading alone (name, kind, place, project) is what a lookup finds.
    return parts(heading, "\n".join(meaning)), parts(f"{heading}, details", "\n".join(detail)) if detail else []
