"""Plain chunk text for embedding (plan RE-08, decisions 6 and 11; the only style since 0.6.0).

The Markdown of the pages serves readers: links with their targets, trace lines, qualified names.
In a chunk, that apparatus fills the embedding window (45% of the characters, RE-01), and the
production stack cuts long chunks into windows that lose their heading. In the plain style:
- **text:** links reduced to their labels, no trace line (the metadata holds the provenance), no
  Markdown markers;
- **heading:** what the item is, its name (a requirement's id and text when it has no name),
  where it is (the last packages of its path) and the project;
- **meaning apart from structure:** an element's meaning (its requirement text, documentation,
  relationships, diagrams) first, its structural detail (members, tagged values) after it, in
  the same chunk when the whole fits in one part, else in a details chunk of its own. (A short
  details chunk is mostly heading, so it outranks the element's meaning for its name: RE-08.)
  Sections are built as data and rendered here as plain text (`sections`), not parsed back out
  of the page Markdown (AR-003R2); `plain()` is for Markdown lines made elsewhere.
- **parts:** text that won't fit in one embedding window is split at line boundaries, each part
  repeating the heading, so that every window says whose text it is. The budget is in tokens,
  estimated (`tokens`), since text dense with ids makes two or three times more tokens per
  character than prose; it leaves room for the source line that `rag/` files end with.
"""

from __future__ import annotations

import math
import re

from .text import md_plain, strip_links

WINDOW = 512  # the embedding window parts are made for (e5, bge, ember-v1)
SOURCE = 100  # tokens left free for a rag/ file's source line (a trace locator: 70 to 80 tokens)
BUDGET = WINDOW - SOURCE - 12  # tokens of heading and text per part, as `tokens` estimates them
HEADING = BUDGET // 4  # the most a heading may take of a part (AR-004R2)
_TOKEN = re.compile(r"[A-Za-z]+|[0-9]+|[^\sA-Za-z0-9]")
_TRACE = re.compile(r"[ \t]*<sub>trace: `[^`]*`</sub>[ \t]*")
# Emit's emphasis, and only that, so that model text keeps its operators (AR-003): bold around a
# label or name ("**Kind:**", "**REQ-1**"), a member's role in italics ("- *part* ..."), an
# annotation's origin ("_(generated by ...)_").
_BOLD = re.compile(r"(?<![\w*\\])\*\*(?=\S)((?:[^*\n\\]|\\.)+?)(?<=\S)\*\*(?![\w*])")
_ROLE = re.compile(r"^(\s*- )\*(?=\S)([^*\n]+?)(?<=\S)\* ", re.MULTILINE)
_ORIGIN = re.compile(r"(?<!\w)_\(([^)\n]*)\)_")


def tokens(text: str) -> int:
    """About how many tokens a 512-token embedding model makes of `text`. Fitted to the
    tokenizer of multilingual-e5-large on the samples' chunks (words, long words, digits,
    punctuation), then raised by a fifth, so that it is too low for fewer than 4% of chunks."""
    n = 0.0
    for w in _TOKEN.findall(text):
        if w[0].isalpha():
            n += 1.07 + 0.415 * max(0, len(w) - 6)
        elif w[0].isdigit():
            n += 0.42 + 0.375 * len(w)
        else:
            n += 0.95
    return math.ceil(1.2 * n)


def _cut(line: str, room: int) -> tuple[str, str]:
    """A line too long for a part: as much of it as fits in `room` tokens (at a space where
    there is one in its second half), and the rest."""
    lo, hi = 1, len(line)
    while lo < hi:  # the longest prefix that fits
        mid = (lo + hi + 1) // 2
        if tokens(line[:mid]) <= room:
            lo = mid
        else:
            hi = mid - 1
    space = line.rfind(" ", 0, lo + 1)
    end = space if space > lo // 2 else lo
    return line[:end].rstrip(), line[end:].lstrip()


def plain(md: str) -> str:
    """Markdown as plain text: links to their labels, no trace lines, no emphasis or code marks.
    Only the markup emit writes is removed; model text keeps its characters."""
    text = _TRACE.sub("", md)
    text = strip_links(text)
    text = _BOLD.sub(r"\1", text)
    text = _ROLE.sub(r"\1\2 ", text)
    text = _ORIGIN.sub(r"(\1)", text)
    text = text.replace("```", "").replace("`", "")
    text = md_plain(text)
    return re.sub(r"\n{3,}", "\n\n", text).strip()


def cap(text: str, limit: int = HEADING, more: str = " …", keep: str = " (project ") -> str:
    """`text` cut at a word to about `limit` estimated tokens, the cut marked with `more`. What
    follows the last `keep` stays whole: a heading's project, which says where its text comes
    from."""
    if tokens(text) <= limit:
        return text
    head, sep, tail = text.rpartition(keep) if keep and keep in text else (text, "", "")
    tail = sep + tail
    return _cut(head, max(limit - tokens(tail) - tokens(more), 1))[0].rstrip(" ;,") + more + tail


def where(owner: str, project: str) -> str:
    """'in A::B::C (project X)': the last three packages of the owner's qualified name, and the
    project."""
    path = "::".join(owner.split("::")[-3:]) if owner else ""
    return (f"in {path} " if path else "") + f"(project {project})"


def parts(heading: str, text: str, budget: int = BUDGET) -> list[str]:
    """`text` under `heading`, split at line boundaries into parts of at most about `budget`
    tokens with the heading (and its part number), each repeating the heading. A heading longer
    than a quarter of the budget is cut."""
    heading = cap(heading, budget // 4)
    room = max(budget - tokens(heading) - 8, 40)
    out: list[list[str]] = [[]]
    size = 0
    for line in text.splitlines():
        while tokens(line) > room:  # a line too long for any part: cut it
            head, line = _cut(line, room)
            if out[-1]:
                out.append([])
            out[-1].append(head)
            out.append([])
            size = 0
        n = tokens(line) + 1
        if size + n > room and out[-1]:
            out.append([])
            size = 0
        out[-1].append(line)
        size += n
    # Blank lines go from a part's ends, but not its first line's indentation: a part that starts
    # inside a nested list (a thread, members) keeps its nesting.
    chunks = [re.sub(r"\A(?:[ \t]*\n)+", "", "\n".join(p)).rstrip() for p in out]
    chunks = [c for c in chunks if c]
    if len(chunks) <= 1:
        return [f"{heading}\n\n{chunks[0]}" if chunks else heading]
    return [f"{heading} (part {k} of {len(chunks)})\n\n{c}" for k, c in enumerate(chunks, 1)]


def parts_with_context(heading: str, lines: list[str], context: list[list[str]], budget: int = BUDGET) -> list[str]:
    """As `parts`, for a nested list: a part that starts at line i starts with `context[i]`, the
    lines it needs to be read alone (its ancestors, say)."""
    heading = cap(heading, budget // 4)
    room = max(budget - tokens(heading) - 8, 40)
    out: list[list[str]] = [[]]
    size = 0
    for i, line in enumerate(lines):
        n = tokens(line) + 1
        if size + n > room and out[-1]:
            out.append(context[i][:])
            size = sum(tokens(c) + 1 for c in context[i])
        while tokens(line) > max(room - size, 20):  # a line too long for any part: cut it
            head, line = _cut(line, max(room - size, 20))
            out[-1].append(head)
            out.append(context[i][:])
            size = sum(tokens(c) + 1 for c in context[i])
        out[-1].append(line)
        size += tokens(line) + 1
    texts = [re.sub(r"\A(?:[ \t]*\n)+", "", "\n".join(p)).rstrip() for p in out]
    texts = [t for t in texts if t]
    if len(texts) <= 1:
        return [f"{heading}\n\n{texts[0]}" if texts else heading]
    return [f"{heading} (part {k} of {len(texts)})\n\n{t}" for k, t in enumerate(texts, 1)]


def pack[K](rows: list[tuple[K, str]], header: str, budget: int = BUDGET, max_rows: int = 60) -> list[list[tuple[K, str]]]:
    """Rows (a key and a line of text each) into parts, in order, that fit an embedding window
    under a header as long as `header` (the longest a part's header gets), at most `max_rows` a
    part (AR-015R2)."""
    limit = budget - tokens(header) - 4
    out: list[list[tuple[K, str]]] = [[]]
    size = 0
    for key, row in rows:
        n = tokens(row) + 1
        if out[-1] and (len(out[-1]) >= max_rows or size + n > limit):
            out.append([])
            size = 0
        out[-1].append((key, row))
        size += n
    return [p for p in out if p]


